package com.aa.coolreads.User.models;

public enum NotificationType {
    POST_NOTIFICATION,
    FRIEND_REQUEST_NOTIFICATION,
    FRIEND_REQUEST_ACCEPTED_NOTIFICATION,
    FRIEND_REVIEWED_BOOK_NOTIFICATION,
    FRIEND_STARRED_BOOK_NOTIFICATION
}
